### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by iacore**
Add placeholder for the downloads table without JS. 

I was confused by it.

### CODE REVIEW

**Comment by tizoc** [comment]
Thank you! That table needs a big update, because now there is a split between ports that already support the new S-series kernels and the ones that don't.

**Comment by iacore** [comment]
What's the S-series kernels?

**Comment by tizoc** [comment]
See https://shenlanguage.org/s-series.html

**Comment by iacore** [comment]
There's still a large delay when the javascript is available, to load the table. During the delay, nothing is shown at all.

**Pull request merged**
